export const OPEN = 'OPEN';
export const CLOSE = 'CLOSE';
export const SAVE_FILE_IN_PROGRESS = 'SAVE_FILE_IN_PROGRESS';
export const SAVE_FILE_COMPLETED = 'SAVE_FILE_COMPLETED';
export const SAVE_FILE_ERRORED = 'SAVE_FILE_ERRORED';
